version: '3'
services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3306:3306
  web:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ./
    container_name: web
    image: web
    ports:
      - 80:80
    volumes:
      - .:/home/app
    depends_on:
      - db
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    container_name: php
    image: php
    volumes:
      - .:/home/app
    depends_on:
      - db
